/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD1;

import java.util.List;




public class App {

    public static void question21() {
        IPaire<Integer, String> p1 = new Paire<>(1, "un");
        System.out.println(p1);
        IPaire<Double, String> p2 = p1.changeFst(1.0);
        System.out.println(p2);
        IPaire<Double, IPaire<Integer, String>> p3 = p2.changeSnd(p1);
        System.out.println(p3);
    }



    public static void exercice4() {
        DAO data = DAO.instance();
        // commandes (non normalisées puis normalisées)
        for (Commande c : data.commandes()) {
            System.out.println(c);
        }
        for (Commande c : data.commandes()) {
            System.out.println(c.normaliser());
        }
        // produits
        System.out.println(data.produits());
        // produits à TVA réduite (3 versions)
        System.out.println(data.selectionProduits(p -> p.cat() == Categorie.REDUIT));
        System.out.println(data.selectionProduits(p -> App.aTauxReduit(p)));
        System.out.println(data.selectionProduits(App::aTauxReduit));
        // produits à TVA réduite coûtant plus de 5 EUR
        System.out.println(data.selectionProduits(p -> p.cat() == Categorie.REDUIT && p.prix() > 5.0));
        // commandes de plus de 2 items
        System.out.println(data.selectionCommande(c -> c.lignes().size() > 2));
        // commandes contenant au moins un produit à TVA réduite commandé en plus de 2
        // exemplaires
        System.out.println(
                data.selectionCommandeSurExistanceLigne(l -> l.fst().cat() == Categorie.REDUIT && l.snd() > 2));
        // affichage des commandes sans réduction
        for (Commande c : data.commandes()) {
            System.out.println(c.affiche(App::calculSimple));
        }
        // affichage des commandes avec réduction
        for (Commande c : data.commandes()) {
            System.out.println(c.affiche(App::calculReduction));
        }
    }

    public static Boolean aTauxReduit(Produit p) {
        return p.cat() == Categorie.REDUIT;
    }

    /**
     * prix TTC = prix unitaire * (1 + taux TVA) * qté
     */
    public static Double calculSimple(Paire<Produit, Integer> ligne) {
        Produit p = ligne.fst();
        int qte = ligne.snd();
        return p.prix() * (1 + p.cat().tva()) * qte;
    }

    /**
     * réduction = si qté > 2 alors prix unitaire sinon 0 prix TTC = prix unitaire *
     * (1 + taux TVA) * qté - réduction
     */
    public static Double calculReduction(Paire<Produit, Integer> ligne) {
        Double reduction = (ligne.snd() > 2) ? ligne.fst().prix() : 0.0;
        return calculSimple(ligne) - reduction;
    }

    public static void main(final String[] args) {

        exercice4();
    }
}
